### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [Dids/clobber#16]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by Dids** [comment]
Thanks, I appreciate the heads up on this, probably wouldn't have figured it out for a while if you hadn't mentioned it. :)

It's fixed now on master, and I'll push a new release later.
