### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SavageAUS** [Dids/clobber#17]
Not sure if this is a clobber issue or due to me running it on Catalina.

 ___    _      _____  ___    ___    ___    ___
(  _`\ ( )    (  _  )(  _`\ (  _`\ (  _`\ |  _`\
| ( (_)| |    | ( ) || (_) )| (_) )| (_(_)| (_) )
| |  _ | |  _ | | | ||  _ <'|  _ <'|  _)_ | ,  /
| (_( )| |_( )| (_) || (_) )| (_) )| (_( )| |\ \
(____/'(____/'(_____)(____/'(____/'(____/'(_) (_)
                                  v0.3.3 by @Dids

✔ Verifying folder structure  
✔ Verifying folder structure  
✔ Verifying EDK is up to date  
✔ Verifying Clover is up to date   
✔ Building base tools   
✔ Setting up EDK  
◌ Linking nasm ⠼ 

Error: Failure detected, aborting

See the log file for more details:
/Users/shane/.clobber/logs/clobber.log
[clobber.log](https://github.com/Dids/clobber/files/3709736/clobber.log)

**Comment by Dids** [comment]
Hmm, almost sounds like `nasm` is bundled with Catalina, unless it was installed by something else you use, like a different Clover build script or something?

Either way, I should be able to check for `nasm` before attempting to install it from Homebrew.

**Comment by Dids** [comment]
@SavageAUS Can you try the following and let me know if it fixes it.

Uninstall clobber:
> brew remove clobber --force

Install clobber (bleeding edge):
> brew install clobber --HEAD

Run clobber again:
> clobber

**Comment by SavageAUS** [comment]
Thanks @Dids that worked for me yesterday, just didn't have time to post here.
I will run again today and make sure all is good.
