### ISSUE TITLE
OcQuirks and FWRunTimeServices.efi. 

### ISSUE THREAD

**Issue by ReddestDream** [Dids/clobber#19]
I’m planning to make some big changes to OcQuirks to support plist settings loading. As part of this, I no longer plan to include FWRuntimeServices.efi in the Release zip. Please pull it from Acidanthera’s AppleSupportPkg Release. I will maintain compatibility with this release version: https://github.com/acidanthera/AppleSupportPkg/releases

In addition I plan to add a default plist to the OcQuirks release zip that is to be located in the same directory as OcQuirks.efi itself. Please copy all the files from the release zip in order to support this. The proposed file structure will be a zip file containing a folder containing both OcQuirks.efi and OcQuirks.plist which will need to be moved to the appropriate location together.

For now, I am unable to make any changes to the OcQuirks release files as doing so breaks Clobber packaging entirely. I figured I would let you know my plans first before making breaking changes. Thanks!

**Comment by Dids** [comment]
Fixed in https://github.com/Dids/clobber/releases/tag/v0.3.6

**Comment by ReddestDream** [comment]
Thx! I’m out now, but when I get back in an hour or two I’ll update OcQuirks and we’ll see how it all goes. :)
