### ISSUE TITLE
Not pulling clover sources( Won't build )

### ISSUE THREAD

**Issue by lyons88** [Dids/clobber#9]
Doesn't seem to be pulling clover, just says it's downloading and returns me to the command prompt immediately.

`jam$ clobber
 ___    _      _____  ___    ___    ___    ___
(  _`\ ( )    (  _  )(  _`\ (  _`\ (  _`\ |  _`\
| ( (_)| |    | ( ) || (_) )| (_) )| (_(_)| (_) )
| |  _ | |  _ | | | ||  _ <'|  _ <'|  _)_ | ,  /
| (_( )| |_( )| (_) || (_) )| (_) )| (_( )| |\ \
(____/'(____/'(_____)(____/'(____/'(____/'(_) (_)
                                  v0.1.4 by @Dids

✔ Verifying folder structure  
✔ Verifying UDK2018 is up to date  
◌ Downloading Clover ⠹ :~ jam$ `

**Comment by Dids** [comment]
Try running with `clobber --verbose` to further debug it. Build logs can also be found in `~/.clobber/logs`. Also which OS version are you running?

**Comment by lyons88** [comment]
I'm trying to build on 10.11.6, seems I'm have trouble with SSL.

`ime="2018-11-15T07:25:52-05:00" level=debug msg="Target Clover revision:HEAD"
✔ Verifying folder structure  
time="2018-11-15T07:25:52-05:00" level=debug msg="Verifying UDK2018 is up to date.."
time="2018-11-15T07:25:52-05:00" level=debug msg="Running command: 'cd /Users/jam/.clobber/src/edk2 && git clean -fdx --exclude="Clover/"'"
time="2018-11-15T07:25:52-05:00" level=debug msg="Command finished with output:
"
✔ Verifying UDK2018 is up to date  
time="2018-11-15T07:25:52-05:00" level=debug msg="Clover is missing, downloading.."
time="2018-11-15T07:25:52-05:00" level=debug msg="Running command: 'svn co https://svn.code.sf.net/p/cloverefiboot/code /Users/jam/.clobber/src/edk2/Clover'"
time="2018-11-15T07:25:52-05:00" level=fatal msg="Error: Failed to run 'svn co https://svn.code.sf.net/p/cloverefiboot/code /Users/jam/.clobber/src/edk2/Clover':
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/cloverefiboot/code'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted`

**Comment by Dids** [comment]
Try running this manually: `svn list https://svn.code.sf.net/p/cloverefiboot/code`

**Comment by lyons88** [comment]
Thanks, I just had to run the svn co https://svn.code.sf.net/p/cloverefiboot/code /Users/jam/.clobber/src/edk2/Clover command and accept the certificate.
